#    ███████╗██╗  ██╗ ██████╗ ██████╗ ████████╗ ██████╗███╗   ███╗██████╗ ███████╗
#    ██╔════╝██║  ██║██╔═══██╗██╔══██╗╚══██╔══╝██╔════╝████╗ ████║██╔══██╗██╔════╝
#    ███████╗███████║██║   ██║██████╔╝   ██║   ██║     ██╔████╔██║██║  ██║███████╗
#    ╚════██║██╔══██║██║   ██║██╔══██╗   ██║   ██║     ██║╚██╔╝██║██║  ██║╚════██║
#    ███████║██║  ██║╚██████╔╝██║  ██║   ██║   ╚██████╗██║ ╚═╝ ██║██████╔╝███████║
#    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝   ╚═╝    ╚═════╝╚═╝     ╚═╝╚═════╝ ╚══════╝

#                         Thank you for downloading ShortCMDs!
#                    If you need any help join discord.strawlandia.it
#                   Remember that this is a BETA version of the plugin
#                  So bugs ARE expected. Please report the in my Discord.

#  ______________________________________
# /                                      \
# |                                      |
# |            Creative Mode             |
# |                                      |
# \______________________________________/

Creative-Message: "&aYou updated your game mode to &6&lCREATIVE"
Creative-No-Permission: "&4You don't have enough permissions to execute this command"
Creative-Player-Offline: "&4The player doesn't exist or is offline"
Successfully-Creative-Player: "&aYou updated the player's game mode to &6&lCREATIVE"
Successfully-Got-Creative: "&aA player updated your game mode to &6&lCREATIVE"

#  ______________________________________
# /                                      \
# |                                      |
# |            Survival Mode             |
# |                                      |
# \______________________________________/

Survival-Message: "&aYou updated your game mode to &6&lSURVIVAL"
Survival-No-Permission: "&4You don't have enough permissions to execute this command"
Survival-Player-Offline: "&4The player doesn't exist or is offline"
Successfully-Survival-Player: "&aYou updated the player's game mode to &6&lCREATIVE"
Successfully-Got-Survival: "&aA player updated your game mode to &6&lCREATIVE"

#  ______________________________________
# /                                      \
# |                                      |
# |            Feed Comand               |
# |                                      |
# \______________________________________/

Feed-Message: "&aYou're not hungry anymore ;D"
Feed-No-Permission: "&4You don't have enough permissions to execute this command"
Feed-Player-Offline: "&4The player doesn't exist or is offline"
Successfully-Fed-Player: "&aYou fed the player"
Successfully-Got-Fed: "&aA player fed you"

#  ______________________________________
# /                                      \
# |                                      |
# |            God Comand                |
# |                                      |
# \______________________________________/

GodMode-Enabled: "&aYou enabled god mode"
GodMode-Disabled: "&4You disabled god mode"
GodMode-No-Permission: "&4You don't have enough permissions to execute this command"
GodMode-Player-Offline: "&4The player doesn't exist or is offline"
Successfully-GodMode-Player: "&aYou enabled god mode to the player"
Successfully-Got-GodMode: "&aA player enabled you god mode"
Successfully-Got-Disabled-GodMode: "&4A player disabled you god mode"
Successfully-Disabled-GodMode-Player: "&4You disabled god mode to a player"