name: ShortCMDs
version: '1.0'
main: me.mefyy.shortcmds.Main
api-version: 1.19
authors: [ Mefyy ]
description: Short commands for Minecraft
commands:
  god:
    description: Become invincible.
    usage: /<command>
  feed:
    description: Set your hunger to max.
    usage: /<command>
  gmc:
    description: Sets your game mode to creative.
    usage: /<command>
  gms:
    description: Sets your game mode to survival.
    usage: /<command>
  shortcmds:
    description: Info of the plugin
    usage: /<command>
